window.messages = {
    en: {
      message: {
        home: 'Home',
        doctors: 'Doctors',
        about: 'About us',
        blog: 'Blog',
        news: 'News',

        contact: 'Contact Us',
        learn: 'Learn Something New',
        every: 'Everyday Anyday Anytime',
        login: 'login',
        email: 'Email',
        password: 'password',
        forget: 'forget password',
        signin: 'sign in',
        or_continue_with: 'or_continue_with',
        register_new_account: 'register_new_account',
        please_enter_your_data_to_create_account:'please_enter_your_data_to_create_account',
        re_password: 're_password',
        phone_number: 'phone_number',
        sign_up: 'sign_up',
        I_have_an_account: 'I_have_an_account',
        please_enter_registered_email_id: 'please_enter_registered_email_id',
        next: 'next',
        I_will_try_again: 'I_will_try_again?',
        please_enter_your_verfication_code: 'please_enter_your_verfication_code',
        done: 'done',
        i_dont_recieve_emails: 'i_don’t_recieve_emails',
        resend: 'resend',
        please_enter_a_new_password: 'please_enter_a_new_password',
        new_password: 'new_password',
        re_new_password: 're_new_password',
        change_password: 'change-password',
        i_remember_my_password: 'i_remember_my_password',
        doctors: 'doctors',
        laboratories: 'laboratories',
        x_ray_centers: 'x_ray_centers',
        hospitals: 'hospitals',
        pharmacies: 'pharmacies',
        favorite: 'favorite',
        settings: 'settings',
        language: 'language',
        arabic: 'arabic',
        terms_and_conditions: 'terms_and_conditions',
        save: 'save',
        discount: 'discount',
        send: 'send',
        subject: 'subject',
        your_email: 'your_email',
        your_name: 'your_name',
        we_are_happy: 'we_are_happy',
      }
    },
    ar: {
      message: {
        home: 'الرئيسيه',
        doctors: 'الاطباء',
        about: 'معلومات عنا',
        blog: 'مدونه',
        news: 'الاخبار',
        contact: 'تواصل معنا',
        learn: 'تعلم شئ جديد',
        every: 'كل يوم اي يوم اي وقت',
        login: 'يرجي تسجيل الدخول الي حسابك',
        email: 'البريد الالكتروني ',
        password: 'كلمه السر',
        forget: 'نسيت كلمه السر',
        signin: 'تسجيل الدخول',
        or_continue_with: 'او يمكنك التواصل من خلال',
        register_new_account: 'تسجيل حساب جديد',
        please_enter_your_data_to_create_account: 'يرجي ادخال البيانات لتسجيل حساب جديد',
        re_password: 'إعادة كلمة السر',
        phone_number: 'رقم الهاتف',
        sign_up: 'انشاء حساب',
        I_have_an_account: 'لدي حساب',
        please_enter_registered_email_id: 'يرجي ادخال بريد الكتروني مسجل بالفعل',
        next: 'التالي',
        I_will_try_again: 'محاولة مرة اخري',
        please_enter_your_verfication_code: 'يرجي ادخال الكود المرسل',
        done: 'تم',
        i_dont_recieve_emails: 'لم استلم الرسالة',
        resend: 'إعادة ارسال',
        please_enter_a_new_password: 'يرجي تعيين كلمة السر الجديدة',
        new_password: 'كلمة السر الجديدة',
        re_new_password: 'إعادة كلمة السر الجديدة',
        change_password: 'تغيير كلمة السر ',
        i_remember_my_password: 'أتذكر كلمة السر',
        doctors: 'اطباء',
        laboratories: 'معامل',
        x_ray_centers:'مراكز أشعة',
        hospitals: 'مستشفيات',
        pharmacies: 'صيدليات',
        favorite: 'المفضلات',
        settings: 'الاعدادات',
        language: 'اللغه',
        arabic: 'العربية',
        terms_and_conditions: 'الاحكام والشروط',
        save: 'تسجيل',
        discount: 'خصم',
        send: 'ارسال',
        subject: 'الموضوع',
        your_email: 'البريد الالكتروني',
        your_name: 'الاسم',
        we_are_happy: 'نحن سعداء لتواصلك معنا',






      

      }
    }
  };