window.messages = {
    en: {
      message: {
        home: 'Home',
        doctors: 'Doctors',
        about: 'About us',
        blog: 'Blog',
        news: 'News',
        contact: 'Contact Us',
        learn: 'Learn Something New',
        every: 'Everyday Anyday Anytime',
        // login
        login: 'login',
        hi: 'Hi there',
        login_paragraph: 'There are many variations of passages of Lorem Ipsum available, some form .',
        email: 'Email Address',
        password: 'password',
        remember_me: 'Remember Me',
        forget: 'forget password',
        signin: 'sign in',
        no_account: 'Don\'t have an account ?',
        or_continue_with: 'Or continue with',
        trust: 'We Trust',
        care: 'We Care',
        // help
        help: 'HELP',
        help_paragraph: 'There are many variations of passages of Lorem Ipsum available, some form .',
        //
        agree: 'i agree to the terms & conditions and privacy policy',
        register_new_account: 'register new account',
        please_enter_your_data_to_create_account:'please_enter_your_data_to_create_account',
        re_password: 're-password',
        phone_number: 'phone number',
        sign_up: 'sign up',
        I_have_an_account: 'I_have_an_account',
        have_an_account: 'have an account',
        please_enter_registered_email_id: 'please_enter_registered_email_id',
        next: 'next',
        I_will_try_again: 'I will try again?',
        please_enter_your_verfication_code: 'please_enter_your_verfication_code',
        done: 'done',
        i_dont_recieve_emails: 'i don’t recieve emails',
        resend: 'resend',
        please_enter_a_new_password: 'please_enter_a_new_password',
        new_password: 'new password',
        re_new_password: 'renew password',
        change_password: 'change-password',
        i_remember_my_password: 'i remember my password',
        doctors: 'doctors',
        laboratories: 'laboratories',
        x_ray_centers: 'x_ray_centers',
        hospitals: 'hospitals',
        pharmacies: 'pharmacies',
        favorite: 'favorite',
        settings: 'settings',
        language: 'language',
        arabic: 'arabic',
        terms_and_conditions: 'terms_and_conditions',
        save: 'save',
        discount: 'discount',
        send: 'send',
        subject: 'subject',
        your_email: 'your_email',
        your_name: 'your_name',
        we_are_happy: 'we_are_happy',
      }
    },
    ar: {
      message: {
        home: 'الرئيسيه',
        doctors: 'الاطباء',
        about: 'معلومات عنا',
        blog: 'مدونه',
        news: 'الاخبار',
        contact: 'تواصل معنا',
        learn: 'تعلم شئ جديد',
        every: 'كل يوم اي يوم اي وقت',
        // login
        login: 'تسجيل الدخول',
        hi: 'اهلا بك',
        login_paragraph: 'اهلا بك فى تريت ميديكال تعرفغ على افضل الاطباء و المسنشفيات و المعامل و المراكز الطبيه التى تساهم فى حل مشاكلك و الوصول للمطلوب و تشرفنا بك',
        remember_me: 'تذكرنى',
        no_account: 'ليس لدى حساب',
        email: 'البريد الالكتروني ',
        password: 'كلمه السر',
        forget: 'نسيت كلمه السر',
        signin: 'تسجيل الدخول',
        trust: 'نحن نرعاك',
        care: 'نحن نهتم بك',
        or_continue_with: 'او يمكنك التواصل من خلال',
        agree: 'انا اوافق على الشروط و الاحكام و خصائص الملكيه',
        have_an_account : 'لدى حساب',
        //help
        help: 'مساعده',
        help_paragraph: 'هناك العديد من المتغيرات و المستشفيات و المعامل و الاطباء و الحصول على افضل دعم و افضل جوده و رقى و مساعده و مساهمه',
        register_new_account: 'تسجيل حساب جديد',
        please_enter_your_data_to_create_account: 'يرجي ادخال البيانات لتسجيل حساب جديد',
        re_password: 'إعادة كلمة السر',
        phone_number: 'رقم الهاتف',
        sign_up: 'انشاء حساب',
        I_have_an_account: 'لدي حساب',
        please_enter_registered_email_id: 'يرجي ادخال بريد الكتروني مسجل بالفعل',
        next: 'التالي',
        I_will_try_again: 'محاولة مرة اخري',
        please_enter_your_verfication_code: 'يرجي ادخال الكود المرسل',
        done: 'تم',
        i_dont_recieve_emails: 'لم استلم الرسالة',
        resend: 'إعادة ارسال',
        please_enter_a_new_password: 'يرجي تعيين كلمة السر الجديدة',
        new_password: 'كلمة السر الجديدة',
        re_new_password: 'إعادة كلمة السر الجديدة',
        change_password: 'تغيير كلمة السر ',
        i_remember_my_password: 'أتذكر كلمة السر',
        doctors: 'اطباء',
        laboratories: 'معامل',
        x_ray_centers:'مراكز أشعة',
        hospitals: 'مستشفيات',
        pharmacies: 'صيدليات',
        favorite: 'المفضلات',
        settings: 'الاعدادات',
        language: 'اللغه',
        arabic: 'العربية',
        terms_and_conditions: 'الاحكام والشروط',
        save: 'تسجيل',
        discount: 'خصم',
        send: 'ارسال',
        subject: 'الموضوع',
        your_email: 'البريد الالكتروني',
        your_name: 'الاسم',
        we_are_happy: 'نحن سعداء لتواصلك معنا',






      

      }
    }
  };